### ISSUE TITLE
[FEATURE] Ability to expand hero image

### ISSUE THREAD

**Issue by oleteacher** [GetPublii/theme-Starter#1]
Nice themes guys! Really like Publii.

Was testing the starter theme and noticed that there was no option for hero to go "full page" or "narrow" as in another theme I tested.

If you could add the option to make hero image full width and move sidebar below it, would be wonderful.

_In the mean time, could you provide the code so I can do this? Have tried but not yet learned the handlebars method. Learning but got little ways to go:)_

**Thank you for sharing Publii**. Have plans to use in classroom for student blogs once I learn more about using and themes.

Susan

**Comment by GetPublii** [comment]
Hi Susan,
I think the Starter layout is not designed to have a Full Page hero section. I'm afraid I will not change it for now.
All you have to do is have both: full and narrow options designed in CSS and then display the clasess (eg. full-hero, narrow-hero) depending on the chosen option.

`<section class="hero {{@config.custom.widthHero}}"> ...`

and into **config.json** file we need to prepare the options that will be displayed in the **{{@config.custom.widthHero}}** place

```
{
     "name": "widthHero",
     "label": "Hero section width",
     "group": "Hero section",
     "value": "full-hero",
     "type": "select",
     "options": [
               {
	          "label": "Full",
	          "value": "full-hero"
	        },				
               {
	          "label": "Narrow",
	          "value": "narrow-hero"
                }]
    },

```

**Comment by oleteacher** [comment]
Thank you. Understood that beauty is in the eye of the beholder but if providing a "starter theme", why not put all the possible options in it so people can learn from them?

Anyway, thank you for your input. Maybe with a little work I could get this into our school system so all can use but it is not quite ready (or i am not).

Cheers!

**Comment by GetPublii** [comment]
I think the including of all the available options in one theme would affect the readability of the code - what does not mean we will not add the new things. 
You can always get help here or via https://publii.ticksy.com/
