### ISSUE TITLE
Rendering process failed

### ISSUE THREAD

**Issue by hojjatabdollahi** [GetPublii/theme-Starter#12]
Hi, I think the theme needs to be updated to be used with the new version of Publii.
I am using the latest version of Publii (v.0.35.3 (build 12104) Beta) but I get the error below. I searched and it looks like this happens if the theme isn't updated. Am I right?

```
Rendering process failed
An error (1002) occurred during parsing index.hbs file.

ENOENT: no such file or directory, open 'C:\Users\Hojjat\Documents\Publii\sites\hojjats-blog\input\themes\starter\assets\css\style.css'
```

**Comment by hojjatabdollahi** [comment]
I found the issue, I just had to change the name of the zip file that I downloaded here to `starter.zip` instead of `theme-Starter-v.1.0.6.0`. Sorry about that.

**Comment by vinyll** [comment]
Same issue here.
Renaming the theme folder to "starter" did the job!
Thanks @hojjatabdollahi
